version: "3.9"
services:

  eshop_api:
    build:
      # Get image details from Dockerfile in ./
      context: .
      dockerfile: Dockerfile
    restart: always
    command: [ "npm", "run", "start" ]
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - '/app/node_modules'
    networks:
      - nginx_eshop-net

networks:
  # connect to network created in a separate
  # nginix container (see nginx/docker-compose.yml)
  nginx_eshop-net:
    external: true