version: "3.9"
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - ./db/data/:/var/lib/postgresql/data

  # eshop_api:
  #   build:
  #     context: .
  #   # command: sh -c 'npm run db'
  #   environment:
  #     DB_CLIENT: ${DB_CLIENT}
  #     DB_USER: ${DB_USER}
  #     DB_PASSWORD: ${DB_PASSWORD}
  #     DB_HOST: ${DB_HOST}
  #     DB_PORT: ${DB_PORT}
  #     DB_NAME: ${DB_NAME}
  #   depends_on:
  #     - postgres
  #   ports:
  #     - '3000:3000'

  adminer:
    depends_on:
      - postgres
    image: adminer
    restart: always
    ports:
      - 8080:8080


