version: "3.9"
services:

  nginx:
    image: nginx:mainline-alpine
    restart: always
    ports:
      - "1080:80" # 80 in nginx redirects to the eshop_api:3000
      - "1081:81" # 81 in nginx redirects to the adminer:8080
    volumes:
      - ./nginx/development:/etc/nginx/conf.d
    networks:
      - eshop-net

networks:
  eshop-net:
